### ISSUE TITLE
autologin for streamers

### ISSUE THREAD

**Issue by Vasir31** [SourceWriters/LoginPlus#20]
can u add autologin system for streamer bcs watchers can see streamer server password

**Comment by Lauriichan** [comment]
How would you add that?
It wouldn't be secure to do that, like for example if the streamer does smth like /autologin, it would ALWAYS relog the accounts name so that doesn't really work I think

**Comment by YellowPhoenix18** [comment]
He probably mean Premium-Login, right?

**Comment by YellowPhoenix18** [comment]
@Vasir31 Can you please answer? Otherwise I will close that issue on 30th of July

**Comment by PSYCHEER** [comment]
made it like not visible, write with closed chat or with empty chat and reading keyboard on background

**Comment by YellowPhoenix18** [comment]
That is something we can not realise with a plugin. If the streamer wants to login they should hide their window or must blurr their chat. This is a plugin and no mod, so blurring chat or hiding it is not posisble, that are client-side features and must be handled by a mod
