### ISSUE TITLE
Ideen zum hinzufügen | LoginPlus

### ISSUE THREAD

**Issue by Banexplain** [SourceWriters/LoginPlus#26]
Hallo und danke, dass man mich auf diese Art der Ideenrückmeldung auf Spigotmc.org hingewiesen hat.
Hier meine Idee:
Ist es möglich in das Plugin eine Funktion einzubauen, dass man sich ingame ausloggt und sich dann wieder anmelden kann(in der Config einstellbar) und für Server die auf Premium laufen eine Funktion hinzuzufügen, die je nachdem ob man Premium oder Offline-Mode ausgewählt hat eine Permission abfrägt - bsp.:
Offline-Mode - Plugin so wie es momentan ist
Online-Mode - Passwort wird nur noch abgefragt, wenn man diese Permission hat.
Mit freundlichen Grüßen
Banexplain - MC: i_r0k_ DC: i_r0k_#2192
[LoginPlus](https://www.spigotmc.org/resources/loginplus.39601/)

**Comment by YellowPhoenix18** [comment]
Hallo,
bitte teile die Fragen vernünftig auf. Es gibt des Weiteren auch bereits Issues die manche deiner Features abdecken. Des Weiteren sollten Issues generell auf englisch sein, sodass andere Leute auch Merge Requests machen können. Die Community kommt größtenteils aus anderen Ländern.
