### ISSUE TITLE
Permanent problems with server after removing plugin

### ISSUE THREAD

**Issue by Silvobi** [SourceWriters/LoginPlus#28]
I tried to unregister myself by deleting some lines from accounts.db/data.db file (I don't excacly remember it's name)
After that I wasn't be able to join server so I decied to delete the plugin. Now I can't move, unless I jump, and adding plugin again makes it doesn't work at all (it don't allow you move, but you can login or register)

**Comment by YellowPhoenix18** [comment]
This is no issue of LoginPlus. The prevention, that you cant move is a event of LoginPlus and that one is only cancelled when the plugin is enabled. So no this must be another plugin.

-> Issue closed
