### ISSUE TITLE
You need to make auto login

### ISSUE THREAD

**Issue by Teiwazik** [SourceWriters/LoginPlus#31]
I think that you need to add auto-login to your plugin, it will increase the usage of the plugin a lot

**Comment by YellowPhoenix18** [comment]
Please give your issue a clear title, that desibes the feature/bug.
Also explain in detail what you expect as feature. This feature-request is hardly to understand and will most likely not been worked on, as it is unclear, what feature and which behaviour is expected.

**Comment by YellowPhoenix18** [comment]
No active feedback, we are closing this issue now
