### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by BabyWaffles** [SourceWriters/LoginPlus#32]
When not logged in:
------------------------
Bug: Players can deal damage to entities and vice versa.
Bug 2: Players can interact with entities. [i.e. Mounting on entities]
------------------------
Server version: 1.18
Server Java kit: openJDK
Server Java version: openjdk 17.0.3
Server JDK Runtime Environment: 64-Bit openJDK build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1
-------------------------------------------End of bug report------------------------------------------------------------

**Comment by YellowPhoenix18** [comment]
If these are two bugs, then open two issues. One bug/feature per issue. Also the "bug-report" should contain a text that describes the issue in general, which is not the case here. This are the reasons, why we close your issue
