### ISSUE TITLE
Session-Timeout

### ISSUE THREAD

**Issue by YellowPhoenix18** [SourceWriters/LoginPlus#4]
Add a session-timeout:

for example if Session timeout is set to 5mins: someone logins to the server and enters their password then exits the server. if 5mins has passed and they enter the server again, they would have to re-enter their password. otherwise if 5mins has not passed, then they dont have to re-enter the password.

Check via IP

**Comment by Ashesh3** [comment]
Any updates on this?

**Comment by YellowPhoenix18** [comment]
If this feature is implemented the issue will get closed and the release-version will be added, please be paitent

**Comment by YellowPhoenix18** [comment]
Will get implemented in v3, which will get released later this day
